FROM debian:buster-slim AS build
RUN apt-get update && apt-get install -y maven
WORKDIR /app
COPY pom.xml .
COPY core ./core
COPY user-service ./user-service
COPY product-service ./product-service
COPY order-service ./order-service
COPY file-service ./file-service
WORKDIR /app/
RUN mvn clean install -DskipTests

FROM openjdk:11-jdk-slim
EXPOSE 5017
ARG JAR_FILE=target/*.jar
COPY --from=build /app/product-service/${JAR_FILE} product-service.jar
ENTRYPOINT ["java","-jar","/product-service.jar"]